services:

  kong1:
    image: kong:latest
    container_name: kong1
    volumes:
      - ./config:/usr/local/kong/declarative
      - ./certs:/certs
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_LOG_LEVEL=debug
      - KONG_WORKER_CONNECTIONS=1024
      - KONG_PLUGINS=bundled
      - KONG_SSL_CERT=/certs/localhost.crt
      - KONG_SSL_CERT_KEY=/certs/localhost.key
    networks:
      - kong-net

  kong2:
    image: kong:latest
    container_name: kong2
    volumes:
      - ./config:/usr/local/kong/declarative
      - ./certs:/certs
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_LOG_LEVEL=debug
      - KONG_WORKER_CONNECTIONS=1024
      - KONG_PLUGINS=bundled
      - KONG_SSL_CERT=/certs/localhost.crt
      - KONG_SSL_CERT_KEY=/certs/localhost.key
    networks:
      - kong-net

  nginx-lb:
    image: nginx
    container_name: kong-lb
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - kong-net
    depends_on:
      - kong1
      - kong2

  service1-1:
      build: ./services/service1
      restart: always
      container_name: service1-1
      ports:
        - "3001:3001"    
      networks:
        - kong-net

  service1-2:
    build: ./services/service1
    restart: always
    container_name: service1-2
    ports:
      - "3002:3001"    
    networks:
      - kong-net

  service1-3:
    build: ./services/service1
    restart: always
    container_name: service1-3
    ports:
      - "3003:3001"    
    networks:
      - kong-net

  service2-1:
    build: ./services/service2
    restart: always
    container_name: service2-1
    ports:
      - "3004:3002"    
    networks:
      - kong-net

  service3-1:
    build: ./services/service3
    restart: always
    container_name: service3-1
    ports:
      - "3005:3003"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
